/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicios;

import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Ejercicio11 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio11
     */
    public Ejercicio11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtEuros = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        chkDolares = new javax.swing.JRadioButton();
        chkLibras = new javax.swing.JRadioButton();
        chkYenes = new javax.swing.JRadioButton();
        chkPesetas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conversor de monedas");

        jLabel2.setText("Seleccione la cantidad en euros:");

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        chkDolares.setText("Convertir a dólares");
        chkDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDolaresActionPerformed(evt);
            }
        });

        chkLibras.setText("Convertir a libras");
        chkLibras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLibrasActionPerformed(evt);
            }
        });

        chkYenes.setText("Convertir a yenes");
        chkYenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkYenesActionPerformed(evt);
            }
        });

        chkPesetas.setText("Convertir a pesetas");
        chkPesetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPesetasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEuros, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConvertir, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkPesetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkDolares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkLibras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkYenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDolares)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkLibras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkYenes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPesetas)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conversion(){
        if(txtEuros.getText().matches("^\\d+(\\.\\d{2})?$")){
            double cant = Double.parseDouble(txtEuros.getText());

            if(chkDolares.isSelected()){
                //Conversion a dolares
                double dol = cant*1.06;
                NumberFormat nf1 = NumberFormat.getCurrencyInstance(Locale.US);
                txtEuros.setText(nf1.format(dol));
            }else if(chkLibras.isSelected()){
                //Conversion a libras
                double lib = cant*0.88;
                NumberFormat nf2 = NumberFormat.getCurrencyInstance(Locale.UK);
                txtEuros.setText(nf2.format(lib));
            }else if(chkYenes.isSelected()){
                //Conversion a yenes
                double yenes = cant*144.92;
                NumberFormat nf3 = NumberFormat.getCurrencyInstance(Locale.JAPAN);
                txtEuros.setText(nf3.format(yenes));
            }else if(chkPesetas.isSelected()){
                //Conversion a pesetas
                double pst = cant*166.386;
                NumberFormat dF = new DecimalFormat("#.## pts");
                txtEuros.setText(dF.format(pst));
            }else{
                JOptionPane.showMessageDialog(this, "Debes seleccionar una checkbox.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Numero invalido, debe tener dos decimales", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        conversion();
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void chkDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDolaresActionPerformed
        txtEuros.setText("");
        chkLibras.setSelected(false);
        chkPesetas.setSelected(false);
        chkYenes.setSelected(false);
    }//GEN-LAST:event_chkDolaresActionPerformed

    private void chkLibrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLibrasActionPerformed
        txtEuros.setText("");
        chkDolares.setSelected(false);
        chkPesetas.setSelected(false);
        chkYenes.setSelected(false);
    }//GEN-LAST:event_chkLibrasActionPerformed

    private void chkYenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkYenesActionPerformed
        txtEuros.setText("");
        chkLibras.setSelected(false);
        chkPesetas.setSelected(false);
        chkDolares.setSelected(false);
    }//GEN-LAST:event_chkYenesActionPerformed

    private void chkPesetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPesetasActionPerformed
        txtEuros.setText("");
        chkLibras.setSelected(false);
        chkDolares.setSelected(false);
        chkYenes.setSelected(false);
    }//GEN-LAST:event_chkPesetasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JRadioButton chkDolares;
    private javax.swing.JRadioButton chkLibras;
    private javax.swing.JRadioButton chkPesetas;
    private javax.swing.JRadioButton chkYenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtEuros;
    // End of variables declaration//GEN-END:variables
}
