import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.*;

public class frmDados extends javax.swing.JFrame {

    private final List<Dado> dados = List.of(new Dado(1),
                                                new Dado(2),
                                                new Dado(3),
                                                new Dado(4),
                                                new Dado(5),
                                                new Dado(6),
                                                new Dado(7),
                                                new Dado(8),
                                                new Dado(9));
    
    private List<JTextField> numeroDados;
    
    private int numDadosCombo;
    
    public frmDados() {
        initComponents();
        setLocationRelativeTo(null);
        
        rellenarComboBox();
        
        deshabilitarComponentesPanel(pnlJugador1, txtApuestaJugador1, btnJugarJugador1);
        deshabilitarComponentesPanel(pnlJugador2, txtApuestaJugador2, btnJugarJugador2);
        
        pnlDados.setEnabled(false);
        btnLanzarDados.setEnabled(false);
        
        numeroDados = new ArrayList<>();
        
        for(int i = 0 ; i<numDadosCombo;i++){
            numeroDados.get(i).setText(String.valueOf(""));
        }
    }
    
    private void rellenarComboBox(){
        for(Dado i : dados){
            cmbNumDados.addItem(i.numDado());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnJugarDados = new javax.swing.JButton();
        pnlDados = new javax.swing.JPanel();
        btnLanzarDados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDado1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDado2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDado3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDado4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDado5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDado6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDado7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDado8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDado9 = new javax.swing.JTextField();
        pnlJugador1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtPuntosJugador1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtApuestaJugador1 = new javax.swing.JTextField();
        btnJugarJugador1 = new javax.swing.JButton();
        pnlJugador2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtPuntosJugador2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtApuestaJugador2 = new javax.swing.JTextField();
        btnJugarJugador2 = new javax.swing.JButton();
        cmbNumDados = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número de dados:");

        btnJugarDados.setText("Jugar");
        btnJugarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarDadosActionPerformed(evt);
            }
        });

        pnlDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        btnLanzarDados.setText("Lanzar los dados");
        btnLanzarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarDadosActionPerformed(evt);
            }
        });

        jLabel2.setText("Dado 1:");

        txtDado1.setEnabled(false);

        jLabel3.setText("Dado 2:");

        txtDado2.setEnabled(false);

        jLabel4.setText("Dado 3:");

        txtDado3.setEnabled(false);

        jLabel5.setText("Dado 4:");

        txtDado4.setEnabled(false);

        jLabel6.setText("Dado 5:");

        txtDado5.setEnabled(false);

        jLabel7.setText("Dado 6:");

        txtDado6.setEnabled(false);

        jLabel8.setText("Dado 7:");

        txtDado7.setEnabled(false);

        jLabel9.setText("Dado 8:");

        txtDado8.setEnabled(false);

        jLabel10.setText("Dado 9:");

        txtDado9.setEnabled(false);

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addComponent(btnLanzarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDado1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                            .addGroup(pnlDadosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDado3))
                            .addGroup(pnlDadosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDado2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDado5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDadosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDado6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDadosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDado4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(txtDado7))
                            .addGroup(pnlDadosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlDadosLayout.createSequentialGroup()
                                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlDadosLayout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDado8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 9, Short.MAX_VALUE))
                                    .addGroup(pnlDadosLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1)
                                        .addComponent(txtDado9)
                                        .addContainerGap())))))))
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtDado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtDado7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtDado8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDado6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtDado9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLanzarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlJugador1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 1"));

        jLabel11.setText("Puntos:");

        txtPuntosJugador1.setText("0");
        txtPuntosJugador1.setEnabled(false);

        jLabel13.setText("Apuesta:");

        btnJugarJugador1.setText("Jugar");
        btnJugarJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarJugador1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJugador1Layout = new javax.swing.GroupLayout(pnlJugador1);
        pnlJugador1.setLayout(pnlJugador1Layout);
        pnlJugador1Layout.setHorizontalGroup(
            pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJugador1Layout.createSequentialGroup()
                .addGroup(pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlJugador1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnJugarJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlJugador1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPuntosJugador1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlJugador1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApuestaJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlJugador1Layout.setVerticalGroup(
            pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPuntosJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtApuestaJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnJugarJugador1))
        );

        pnlJugador2.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 2"));

        jLabel12.setText("Puntos:");

        txtPuntosJugador2.setText("0");
        txtPuntosJugador2.setEnabled(false);

        jLabel14.setText("Apuesta:");

        btnJugarJugador2.setText("Jugar");
        btnJugarJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarJugador2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJugador2Layout = new javax.swing.GroupLayout(pnlJugador2);
        pnlJugador2.setLayout(pnlJugador2Layout);
        pnlJugador2Layout.setHorizontalGroup(
            pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugador2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPuntosJugador2))
                    .addGroup(pnlJugador2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApuestaJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                    .addComponent(btnJugarJugador2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlJugador2Layout.setVerticalGroup(
            pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugador2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPuntosJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtApuestaJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnJugarJugador2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbNumDados, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJugarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnJugarDados)
                    .addComponent(cmbNumDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarDadosActionPerformed
        habilarComponentesPanel(pnlJugador1, txtApuestaJugador1, btnJugarJugador1);
        this.numDadosCombo = (int) cmbNumDados.getSelectedItem();
        if(!numeroDados.isEmpty()){
            for(JTextField i : numeroDados){
                i.setText("");
            }
        }
        txtApuestaJugador1.setText("");
        txtApuestaJugador2.setText("");
    }//GEN-LAST:event_btnJugarDadosActionPerformed

    private void habilarComponentesPanel(JPanel panel,JTextField txtApuesta, JButton btnJugar){
        if(!panel.isEnabled()){
            panel.setEnabled(true);
            if(!txtApuesta.isEnabled()){
                txtApuesta.setEnabled(true);
            }
            if(!btnJugar.isEnabled()){
                btnJugar.setEnabled(true);
            }
        }
    }
    
    private void deshabilitarComponentesPanel(JPanel panel,JTextField txtApuesta, JButton btnJugar){
        if(panel.isEnabled()){
            panel.setEnabled(false);
            if(txtApuesta.isEnabled()){
                txtApuesta.setEnabled(false);
            }
            if(btnJugar.isEnabled()){
                btnJugar.setEnabled(false);
            }
        }
    }
    
    private boolean esNumero(String num){
        boolean es = false;
        try{
            if(Integer.parseInt(num)>=numDadosCombo && Integer.parseInt(num)<=numDadosCombo*6){
                es = true;
            }
        }catch (NumberFormatException error){
            JOptionPane.showMessageDialog(this, "Número no válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return es;
    }
    
    private void btnJugarJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarJugador1ActionPerformed
        if(esNumero(txtApuestaJugador1.getText())){
            habilarComponentesPanel(pnlJugador2, txtApuestaJugador2, btnJugarJugador2);
            deshabilitarComponentesPanel(pnlJugador1, txtApuestaJugador1, btnJugarJugador1);
        }else{
            JOptionPane.showMessageDialog(this, "Número no válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnJugarJugador1ActionPerformed

    private void btnJugarJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarJugador2ActionPerformed
        Random r = new Random();
        int numAl = r.nextInt(numDadosCombo, numDadosCombo*6+1);
        txtApuestaJugador2.setText(String.valueOf(numAl));
        if(txtApuestaJugador2.getText().equals(txtApuestaJugador1.getText())){
            txtApuestaJugador2.setText(String.valueOf(numAl-1));
        }
        deshabilitarComponentesPanel(pnlJugador2, txtApuestaJugador2, btnJugarJugador2);
        
        btnLanzarDados.setEnabled(true);
        pnlDados.setEnabled(true);
    }//GEN-LAST:event_btnJugarJugador2ActionPerformed

    private void btnLanzarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarDadosActionPerformed
        numeroDados = List.of(txtDado1,
                                  txtDado2,
                                  txtDado3,
                                  txtDado4,
                                  txtDado5,
                                  txtDado6,
                                  txtDado7,
                                  txtDado8,
                                  txtDado9);
        
        int numSum = 0;
        
        for(int i = 0 ; i<numDadosCombo;i++){
            int numAl = new Random().nextInt(1, 7);
            numSum+=numAl;
            numeroDados.get(i).setText(String.valueOf(numAl));
        }
        
        if(Integer.parseInt(txtApuestaJugador1.getText())<numSum && Integer.parseInt(txtApuestaJugador1.getText()) > Integer.parseInt(txtApuestaJugador2.getText())){
            JOptionPane.showMessageDialog(this, "Jugador 1 gana.", "Ganador", JOptionPane.INFORMATION_MESSAGE);
            txtPuntosJugador1.setText(String.valueOf(Integer.parseInt(txtPuntosJugador1.getText())+1));
            btnJugarDadosActionPerformed(evt);
        }else if(Integer.parseInt(txtApuestaJugador2.getText())<numSum && Integer.parseInt(txtApuestaJugador2.getText()) > Integer.parseInt(txtApuestaJugador1.getText())){
            JOptionPane.showMessageDialog(this, "Jugador 2 gana.", "Ganador", JOptionPane.INFORMATION_MESSAGE);
            txtPuntosJugador2.setText(String.valueOf(Integer.parseInt(txtPuntosJugador2.getText())+1));
            btnJugarDadosActionPerformed(evt);
        }
        
        if(Integer.parseInt(txtApuestaJugador1.getText())>numSum && Integer.parseInt(txtApuestaJugador2.getText())>numSum){
            JOptionPane.showMessageDialog(this, "Los dos os pasais. Sigue lanzando los dados.", "Nadie gana.", JOptionPane.INFORMATION_MESSAGE);
        }else if(Integer.parseInt(txtApuestaJugador1.getText())>numSum && Integer.parseInt(txtApuestaJugador2.getText())<numSum){
            JOptionPane.showMessageDialog(this, "Jugador 1 gana.", "Ganador.", JOptionPane.INFORMATION_MESSAGE);
            txtPuntosJugador1.setText(String.valueOf(Integer.parseInt(txtPuntosJugador1.getText())+1));
            btnJugarDadosActionPerformed(evt);
        }else if(Integer.parseInt(txtApuestaJugador1.getText())<numSum && Integer.parseInt(txtApuestaJugador2.getText())>numSum){
            JOptionPane.showMessageDialog(this, "Jugador 2 gana.", "Ganador.", JOptionPane.INFORMATION_MESSAGE);
            txtPuntosJugador2.setText(String.valueOf(Integer.parseInt(txtPuntosJugador2.getText())+1));
            btnJugarDadosActionPerformed(evt);
        }
        
        if(numSum==Integer.parseInt(txtApuestaJugador1.getText())){
            JOptionPane.showMessageDialog(this, "Jugador 1 gana.", "Ganador", JOptionPane.INFORMATION_MESSAGE);
            txtPuntosJugador1.setText(String.valueOf(Integer.parseInt(txtPuntosJugador1.getText())+1));
            btnJugarDadosActionPerformed(evt);
        }else if(numSum==Integer.parseInt(txtApuestaJugador2.getText())){
            JOptionPane.showMessageDialog(this, "Jugador 2 gana.", "Ganador", JOptionPane.INFORMATION_MESSAGE);
            txtPuntosJugador2.setText(String.valueOf(Integer.parseInt(txtPuntosJugador2.getText())+1));
            btnJugarDadosActionPerformed(evt);
        }
    }//GEN-LAST:event_btnLanzarDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugarDados;
    private javax.swing.JButton btnJugarJugador1;
    private javax.swing.JButton btnJugarJugador2;
    private javax.swing.JButton btnLanzarDados;
    private javax.swing.JComboBox<Integer> cmbNumDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlJugador1;
    private javax.swing.JPanel pnlJugador2;
    private javax.swing.JTextField txtApuestaJugador1;
    private javax.swing.JTextField txtApuestaJugador2;
    private javax.swing.JTextField txtDado1;
    private javax.swing.JTextField txtDado2;
    private javax.swing.JTextField txtDado3;
    private javax.swing.JTextField txtDado4;
    private javax.swing.JTextField txtDado5;
    private javax.swing.JTextField txtDado6;
    private javax.swing.JTextField txtDado7;
    private javax.swing.JTextField txtDado8;
    private javax.swing.JTextField txtDado9;
    private javax.swing.JTextField txtPuntosJugador1;
    private javax.swing.JTextField txtPuntosJugador2;
    // End of variables declaration//GEN-END:variables
}
